# Generated by Django 5.1.4 on 2025-03-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymark3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
