# Generated by Django 5.1.4 on 2025-03-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymark3', '0002_signup_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('mg', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
