# Generated by Django 5.1.4 on 2025-04-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymark3', '0003_sign_delete_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Sign',
        ),
    ]
