# Generated by Django 5.1.4 on 2025-04-11 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymark3', '0005_signin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signin',
            old_name='user_name',
            new_name='username',
        ),
    ]
