# Generated by Django 5.1.4 on 2025-05-14 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymark3', '0006_rename_user_name_signin_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='dolist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mymark3.signin'),
            preserve_default=False,
        ),
    ]
