# Generated by Django 5.1.4 on 2025-05-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymark3', '0007_dolist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dolist',
            name='content',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='dolist',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='signin',
            name='password',
            field=models.CharField(max_length=310),
        ),
        migrations.AlterField(
            model_name='signin',
            name='username',
            field=models.CharField(max_length=330),
        ),
    ]
