# Generated by Django 5.1.7 on 2025-05-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymark3', '0008_alter_dolist_content_alter_dolist_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=300)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=300)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Dolist',
        ),
        migrations.DeleteModel(
            name='Signin',
        ),
    ]
