# Generated by Django 5.1.7 on 2025-05-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymark3', '0010_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
