# Generated by Django 5.1.7 on 2025-05-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymark3', '0011_sign_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=330)),
                ('password', models.CharField(max_length=310)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='static/images')),
            ],
        ),
    ]
