# Generated by Django 5.1.7 on 2025-05-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymark3', '0012_log_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_in',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/static/images'),
        ),
    ]
