# Generated by Django 5.1.7 on 2025-05-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymark3', '0015_alter_sign_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='pic',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
