# Generated by Django 5.1.7 on 2025-05-31 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymark3', '0016_alter_sign_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
