# Generated by Django 5.1.7 on 2025-05-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymark3', '0017_alter_sign_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='products',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
