# Generated by Django 5.1.7 on 2025-06-02 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymark3', '0020_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cate_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mymark3.category'),
        ),
    ]
