# Generated by Django 5.1.7 on 2025-06-02 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymark3', '0021_products_cate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cate_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='mymark3.category'),
        ),
    ]
