# Generated by Django 5.1.7 on 2025-06-07 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymark3', '0022_alter_products_cate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='media/static/images')),
            ],
        ),
        migrations.DeleteModel(
            name='Log_in',
        ),
        migrations.AddField(
            model_name='products',
            name='Images_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='mymark3.images_product'),
        ),
        migrations.DeleteModel(
            name='Sign',
        ),
    ]
