# Generated by Django 5.1.7 on 2025-06-07 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymark3', '0023_images_product_delete_log_in_products_images_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Images_product',
        ),
        migrations.AddField(
            model_name='images_product',
            name='img_more',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mymark3.products'),
        ),
    ]
