# Generated by Django 5.1.7 on 2025-06-07 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymark3', '0024_remove_products_images_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images_product',
            name='img_more',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='mymark3.products'),
        ),
    ]
